name: Build and Deploy Web App

on: # Push to main, all PR's
  push:
    branches:
      - main
  pull_request:


jobs:
  build_app:
    name: Build Web App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web-demo

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install Node 
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Change this to whatever version you want 

    - name: Install packages # Anything in the package lock
      run: npm ci
    
    - name: Build app 
      run: yarn build

    - name: Test app # Should kill the workflow if it fails
      run: yarn test --passWithNoTests
    
    - name: Upload build to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: built-app
        path: ./web-demo/build # Have to specify from root here

  deploy_app:
    name: Deploy app
    needs: build_app
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: built-app
        path: ./web-demo/build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build


